// Меню кафе. Каждое текстовое поле: [русский, английский].
// c: раздел, p: цена в тенге, w: выход [число, единица] (g, ml, l, pcs, cm),
// t: метки hit (хит), new (новинка), kids (детям), veg (без мяса), spicy (острое),
// v: варианты порции [{ l: [ru, en], p: цена }], тогда p равна минимальной цене,
// img: имя фото из папки img/ (большое img/<имя>.webp и квадрат img/<имя>-s.webp).
// Фото взяты из Unsplash и Flickr как примеры; для настоящего кафе их стоит заменить своими.

window.CATEGORIES = [
  { id: 'breakfast', n: ['Завтраки', 'Breakfast'], note: ['Подаём до 12:00', 'Served until noon'] },
  { id: 'salads',    n: ['Салаты', 'Salads'] },
  { id: 'soups',     n: ['Супы', 'Soups'] },
  { id: 'mains',     n: ['Горячее', 'Mains'] },
  { id: 'grill',     n: ['Мангал', 'Grill'], note: ['Готовим на углях 20-25 минут', 'Charcoal grilled, 20-25 minutes'] },
  { id: 'pizza',     n: ['Пицца и паста', 'Pizza & pasta'] },
  { id: 'kids',      n: ['Детям', 'Kids'], note: ['К каждому детскому блюду маленький подарок', 'Every kids dish comes with a small gift'] },
  { id: 'desserts',  n: ['Десерты', 'Desserts'] },
  { id: 'drinks',    n: ['Напитки', 'Drinks'] },
];

window.MENU = [
  // Завтраки
  { id: 'pancakes', c: 'breakfast', p: 2400, w: [4, 'pcs'], t: ['hit', 'kids', 'veg'], img: 'pancakes',
    n: ['Панкейки с ягодами', 'Pancakes with berries'],
    d: ['Пышные, с клубникой, вишней и кленовым сиропом', 'Fluffy stack with strawberries, cherries and maple syrup'] },
  { id: 'shakshuka', c: 'breakfast', p: 2600, w: [320, 'g'], t: ['spicy', 'veg'], img: 'shakshuka',
    n: ['Шакшука', 'Shakshuka'],
    d: ['Яйца в томатно-перечном соусе, кинза, тёплая лепёшка', 'Eggs baked in spiced tomato and pepper sauce, coriander, warm flatbread'] },
  { id: 'crepes', c: 'breakfast', p: 1900, w: [3, 'pcs'], t: ['kids', 'veg'], img: 'crepes',
    n: ['Блинчики', 'Crêpes'],
    v: [{ l: ['Со сметаной', 'With sour cream'], p: 1900 }, { l: ['С творогом и апельсином', 'Cottage cheese & orange'], p: 2200 }, { l: ['С курицей и грибами', 'Chicken & mushroom'], p: 2600 }],
    d: ['Тонкие, как у бабушки. Начинку выбираете вы', 'Thin, just like grandma made. You pick the filling'] },
  { id: 'egg-toast', c: 'breakfast', p: 2100, w: [240, 'g'], t: ['veg'], img: 'egg-toast',
    n: ['Тост с глазуньей', 'Fried egg toast'],
    d: ['Зерновой хлеб, авокадо, яйцо, перец халапеньо', 'Grain bread, avocado, sunny egg, jalapeño'] },
  { id: 'avocado-toast', c: 'breakfast', p: 2300, w: [220, 'g'], t: ['veg', 'new'], img: 'avocado-toast',
    n: ['Тосты с авокадо', 'Avocado toast'],
    d: ['Два тоста, крем из авокадо, лимон, семена', 'Two slices, smashed avocado, lemon, seeds'] },
  { id: 'parfait', c: 'breakfast', p: 1500, w: [200, 'g'], t: ['kids', 'veg'], img: 'parfait',
    n: ['Йогурт с клубникой', 'Strawberry yogurt pot'],
    d: ['Домашний йогурт, ягоды, мёд', 'House yogurt, berries, honey'] },
  { id: 'croissant', c: 'breakfast', p: 900, w: [1, 'pcs'], t: ['veg', 'kids'], img: 'croissant',
    n: ['Круассан', 'Croissant'],
    v: [{ l: ['Классический', 'Plain'], p: 900 }, { l: ['С ветчиной и сыром', 'Ham & cheese'], p: 1500 }],
    d: ['Печём каждое утро', 'Baked fresh every morning'] },

  // Салаты
  { id: 'caesar', c: 'salads', p: 2900, w: [250, 'g'], t: ['hit'], img: 'caesar',
    n: ['Цезарь с курицей', 'Chicken Caesar'],
    d: ['Романо, курица гриль, пармезан, гренки, соус Цезарь', 'Romaine, grilled chicken, parmesan, croutons, Caesar dressing'] },
  { id: 'beef-salad', c: 'salads', p: 3400, w: [260, 'g'], t: ['spicy'], img: 'beef-salad',
    n: ['Тёплый салат с говядиной', 'Warm beef salad'],
    d: ['Говядина medium, шпинат, кешью, острый перец, кисло-сладкий соус', 'Medium beef, spinach, cashews, chili, sweet and sour dressing'] },
  { id: 'salmon-bowl', c: 'salads', p: 3600, w: [300, 'g'], t: ['new'], img: 'salmon-bowl',
    n: ['Боул с лососем', 'Salmon bowl'],
    d: ['Лосось, яйцо, кукуруза, краснокочанная капуста, зелень', 'Salmon, egg, sweetcorn, red cabbage, greens'] },
  { id: 'veg-bowl', c: 'salads', p: 2700, w: [300, 'g'], t: ['veg'], img: 'veg-bowl',
    n: ['Овощной боул', 'Veggie bowl'],
    d: ['Авокадо, нут, запечённый батат, томаты, редис', 'Avocado, chickpeas, roast sweet potato, tomatoes, radish'] },
  { id: 'berry-salad', c: 'salads', p: 2600, w: [230, 'g'], t: ['veg'], img: 'berry-salad',
    n: ['Салат с клубникой и фетой', 'Strawberry & feta salad'],
    d: ['Микс салатов, клубника, фета, орехи, бальзамик', 'Mixed leaves, strawberries, feta, nuts, balsamic'] },

  // Супы
  { id: 'borscht', c: 'soups', p: 2200, w: [350, 'ml'], t: ['hit'], img: 'borscht',
    n: ['Борщ', 'Borscht'],
    d: ['На говяжьем бульоне, со сметаной и чесночными пампушками', 'Beef broth, sour cream and garlic buns'] },
  { id: 'pumpkin-soup', c: 'soups', p: 2100, w: [300, 'ml'], t: ['veg', 'kids'], img: 'pumpkin-soup',
    n: ['Тыквенный крем-суп', 'Pumpkin cream soup'],
    d: ['Сливки, тыквенные семечки, капля оливкового масла', 'Cream, pumpkin seeds, a drop of olive oil'] },
  { id: 'tomato-soup', c: 'soups', p: 2000, w: [300, 'ml'], t: ['veg'], img: 'tomato-soup',
    n: ['Томатный суп', 'Tomato soup'],
    d: ['Запечённые томаты, базилик, гренки', 'Roasted tomatoes, basil, croutons'] },
  { id: 'minestrone', c: 'soups', p: 1900, w: [350, 'ml'], t: ['veg'], img: 'minestrone',
    n: ['Овощной суп', 'Vegetable soup'],
    d: ['Фасоль, томаты, кабачок, сельдерей, зелень', 'Beans, tomatoes, zucchini, celery, herbs'] },
  { id: 'noodle-soup', c: 'soups', p: 2800, w: [450, 'ml'], t: ['new', 'spicy'], img: 'noodle-soup',
    n: ['Суп-лапша с креветками', 'Shrimp noodle soup'],
    d: ['Пшеничная лапша, креветки, яйцо, бок-чой', 'Wheat noodles, shrimp, egg, bok choy'] },

  // Горячее
  { id: 'beshbarmak', c: 'mains', p: 4500, w: [450, 'g'], t: ['hit'], img: 'beshbarmak',
    n: ['Бешбармак', 'Beshbarmak'],
    v: [{ l: ['Порция', 'Single'], p: 4500 }, { l: ['На компанию, 4-5 человек', 'To share, 4-5 people'], p: 16900 }],
    d: ['Конина и говядина, тонкое тесто, сочный лук, сорпа отдельно', 'Horse meat and beef, hand-rolled noodles, onion sauce, broth on the side'] },
  { id: 'plov', c: 'mains', p: 3200, w: [350, 'g'], t: ['hit'], img: 'plov',
    n: ['Плов', 'Plov'],
    d: ['Девзира, говядина, жёлтая морковь, нут, чеснок', 'Devzira rice, beef, yellow carrot, chickpeas, garlic'] },
  { id: 'lagman', c: 'mains', p: 3100, w: [400, 'g'], t: ['spicy'], img: 'lagman',
    n: ['Лагман', 'Lagman'],
    v: [{ l: ['Гуйру, жареный', 'Guiru, stir-fried'], p: 3100 }, { l: ['Суп-лагман', 'Soup lagman'], p: 2900 }],
    d: ['Тянутая лапша, говядина, овощи, чесночный уксус', 'Hand-pulled noodles, beef, vegetables, garlic vinegar'] },
  { id: 'manty', c: 'mains', p: 2400, w: [5, 'pcs'], t: [], img: 'manty',
    n: ['Манты', 'Manty'],
    v: [{ l: ['С тыквой', 'Pumpkin'], p: 2400 }, { l: ['С говядиной', 'Beef'], p: 2900 }],
    d: ['Ручная лепка, на пару. Со сметаной или томатным соусом', 'Hand-folded and steamed. With sour cream or tomato sauce'] },
  { id: 'steak', c: 'mains', p: 6900, w: [350, 'g'], t: [], img: 'steak',
    n: ['Стейк с картофелем', 'Steak & fries'],
    d: ['Говяжий стриплойн, картофель по-деревенски, перечный соус', 'Beef striploin, country fries, pepper sauce'] },
  { id: 'salmon', c: 'mains', p: 5900, w: [280, 'g'], t: ['new'], img: 'salmon',
    n: ['Лосось на гриле', 'Grilled salmon'],
    d: ['Стейк лосося, шпинат, лайм, сливочный соус', 'Salmon steak, spinach, lime, cream sauce'] },
  { id: 'chicken-grill', c: 'mains', p: 3300, w: [320, 'g'], t: ['kids'], img: 'chicken-grill',
    n: ['Куриная грудка с овощами', 'Chicken breast & veg'],
    d: ['Сочная, на гриле, с морковью, кабачком и лимоном', 'Juicy, grilled, with carrot, zucchini and lemon'] },
  { id: 'meatballs', c: 'mains', p: 2800, w: [300, 'g'], t: ['kids'], img: 'meatballs',
    n: ['Домашние тефтели', 'Home-style meatballs'],
    d: ['Говядина и индейка, руккола, томатный соус', 'Beef and turkey, rocket, tomato sauce'] },

  // Мангал
  { id: 'lamb-skewer', c: 'grill', p: 3900, w: [200, 'g'], t: ['hit'], img: 'lamb-skewer',
    n: ['Шашлык из баранины', 'Lamb shashlik'],
    d: ['Мякоть с курдючком, маринованный лук, лаваш', 'Lamb with fat tail, pickled onion, lavash'] },
  { id: 'lula', c: 'grill', p: 3400, w: [300, 'g'], t: ['spicy'], img: 'lula',
    n: ['Люля-кебаб с картофелем', 'Lula kebab with fries'],
    v: [{ l: ['Из говядины', 'Beef'], p: 3400 }, { l: ['Из курицы', 'Chicken'], p: 2900 }],
    d: ['Рубленое мясо с зирой, картофель фри, свежие томаты', 'Minced meat with cumin, fries, fresh tomatoes'] },
  { id: 'ribs', c: 'grill', p: 4800, w: [500, 'g'], t: [], img: 'ribs',
    n: ['Свиные рёбрышки BBQ', 'BBQ pork ribs'],
    d: ['Томлёные, потом на углях. Соус барбекю, томаты', 'Slow-cooked, then charcoal grilled. BBQ sauce, tomatoes'] },
  { id: 'platter', c: 'grill', p: 18900, w: [1.8, 'kg'], t: ['hit'], img: 'platter',
    n: ['Мангал на компанию', 'Grill platter to share'],
    d: ['Баранина, курица, люля, овощи на углях, три соуса. На 4-5 человек', 'Lamb, chicken, lula, charred vegetables, three sauces. Feeds 4-5'] },

  // Пицца и паста
  { id: 'meat-pizza', c: 'pizza', p: 3300, w: null, t: ['hit'], img: 'meat-pizza',
    n: ['Мясная пицца', 'Meat feast pizza'],
    v: [{ l: ['25 см', '25 cm'], p: 3300 }, { l: ['32 см', '32 cm'], p: 4400 }],
    d: ['Колбаски, говядина, томаты черри, розмарин', 'Sausage, beef, cherry tomatoes, rosemary'] },
  { id: 'margherita', c: 'pizza', p: 2700, w: null, t: ['veg', 'kids'], img: 'margherita',
    n: ['Маргарита', 'Margherita'],
    v: [{ l: ['25 см', '25 cm'], p: 2700 }, { l: ['32 см', '32 cm'], p: 3600 }],
    d: ['Томатный соус, моцарелла, базилик', 'Tomato sauce, mozzarella, basil'] },
  { id: 'chicken-pizza', c: 'pizza', p: 3000, w: null, t: ['kids'], img: 'chicken-pizza',
    n: ['Пицца с курицей и ананасом', 'Chicken & pineapple pizza'],
    v: [{ l: ['25 см', '25 cm'], p: 3000 }, { l: ['32 см', '32 cm'], p: 4000 }],
    d: ['Курица, ананас, красный лук, моцарелла', 'Chicken, pineapple, red onion, mozzarella'] },
  { id: 'carbonara', c: 'pizza', p: 3100, w: [300, 'g'], t: [], img: 'carbonara',
    n: ['Карбонара', 'Carbonara'],
    d: ['Спагетти, бекон из индейки, желток, пармезан', 'Spaghetti, turkey bacon, egg yolk, parmesan'] },
  { id: 'bolognese', c: 'pizza', p: 2900, w: [320, 'g'], t: ['kids'], img: 'bolognese',
    n: ['Пенне болоньезе', 'Penne bolognese'],
    d: ['Томлёный мясной соус, пармезан', 'Slow-cooked meat sauce, parmesan'] },
  { id: 'shrimp-pasta', c: 'pizza', p: 3900, w: [320, 'g'], t: ['spicy'], img: 'shrimp-pasta',
    n: ['Паста с креветками', 'Shrimp spaghetti'],
    d: ['Тигровые креветки, черри, чеснок, чили', 'Tiger prawns, cherry tomatoes, garlic, chili'] },

  // Детям
  { id: 'nuggets', c: 'kids', p: 1900, w: [200, 'g'], t: ['kids', 'hit'], img: 'nuggets',
    n: ['Наггетсы', 'Chicken nuggets'],
    d: ['Куриное филе в хрустящей панировке, соус на выбор', 'Crispy breaded chicken breast, dip of your choice'] },
  { id: 'burger', c: 'kids', p: 2200, w: [250, 'g'], t: ['kids'], img: 'burger',
    n: ['Мини-бургер', 'Mini burger'],
    d: ['Котлета из говядины, сыр, огурчик, без острого', 'Beef patty, cheese, pickle, nothing spicy'] },
  { id: 'mac', c: 'kids', p: 1500, w: [220, 'g'], t: ['kids', 'veg'], img: 'mac',
    n: ['Макароны с сыром', 'Mac & cheese'],
    d: ['Рожки в сливочно-сырном соусе', 'Macaroni in creamy cheese sauce'] },
  { id: 'fries', c: 'kids', p: 900, w: [150, 'g'], t: ['kids', 'veg'], img: 'fries',
    n: ['Картофель фри', 'French fries'],
    d: ['С кетчупом или сырным соусом', 'With ketchup or cheese sauce'] },

  // Десерты
  { id: 'medovik', c: 'desserts', p: 1700, w: [150, 'g'], t: ['hit', 'veg'], img: 'medovik',
    n: ['Медовик', 'Honey cake'],
    d: ['Восемь коржей и сметанный крем', 'Eight layers with sour cream frosting'] },
  { id: 'cheesecake', c: 'desserts', p: 1900, w: [140, 'g'], t: ['veg'], img: 'cheesecake',
    n: ['Черничный чизкейк', 'Blueberry cheesecake'],
    d: ['Нью-Йорк, с черничным конфи', 'New York style, blueberry compote'] },
  { id: 'raspberry-cake', c: 'desserts', p: 1800, w: [150, 'g'], t: ['veg'], img: 'raspberry-cake',
    n: ['Малиновый торт', 'Raspberry cake'],
    d: ['Бисквит, сливочный крем, свежая малина', 'Sponge, whipped cream, fresh raspberries'] },
  { id: 'chocolate-cake', c: 'desserts', p: 1900, w: [160, 'g'], t: ['veg'], img: 'chocolate-cake',
    n: ['Шоколадный торт', 'Chocolate cake'],
    d: ['Влажный бисквит и ганаш на тёмном шоколаде', 'Moist sponge and dark chocolate ganache'] },
  { id: 'rainbow-cake', c: 'desserts', p: 1600, w: [140, 'g'], t: ['kids', 'veg', 'new'], img: 'rainbow-cake',
    n: ['Торт «Радуга»', 'Rainbow cake'],
    d: ['Шесть цветных коржей. Целый торт на день рождения закажите за сутки', 'Six colourful layers. Order a whole one for a birthday a day ahead'] },
  { id: 'donuts', c: 'desserts', p: 700, w: [1, 'pcs'], t: ['kids', 'veg'], img: 'donuts',
    n: ['Пончик', 'Doughnut'],
    d: ['Шоколадная глазурь и цветная посыпка', 'Chocolate glaze and sprinkles'] },
  { id: 'icecream', c: 'desserts', p: 1200, w: [3, 'scoops'], t: ['kids', 'veg'], img: 'icecream',
    n: ['Мороженое', 'Ice cream'],
    d: ['Пломбир, шоколад или клубника. В вафельном рожке или в креманке', 'Vanilla, chocolate or strawberry. In a cone or a bowl'] },
  { id: 'popsicle', c: 'desserts', p: 800, w: [1, 'pcs'], t: ['kids', 'veg'], img: 'popsicle',
    n: ['Ягодное эскимо', 'Berry popsicle'],
    d: ['Йогурт и вишня, без лишнего сахара', 'Yogurt and cherry, no added sugar'] },

  // Напитки
  { id: 'milk-tea', c: 'drinks', p: 1200, w: null, t: ['hit'], img: 'milk-tea',
    n: ['Чай по-казахски', 'Kazakh tea with milk'],
    v: [{ l: ['Чайник 0,5 л', 'Pot, 0.5 l'], p: 1200 }, { l: ['Чайник 1 л', 'Pot, 1 l'], p: 1900 }],
    d: ['Крепкий чёрный чай со сливками, к нему печенье', 'Strong black tea with cream, served with cookies'] },
  { id: 'teapot', c: 'drinks', p: 1100, w: [0.8, 'l'], t: [], img: 'teapot',
    n: ['Чай в чайнике', 'Pot of tea'],
    d: ['Чёрный, зелёный или жасминовый', 'Black, green or jasmine'] },
  { id: 'herbal-tea', c: 'drinks', p: 1500, w: [0.8, 'l'], t: ['kids'], img: 'herbal-tea',
    n: ['Травяной чай с мёдом', 'Herbal tea with honey'],
    d: ['Мята, чабрец, липа. Без кофеина', 'Mint, thyme, linden. Caffeine-free'] },
  { id: 'cappuccino', c: 'drinks', p: 1100, w: [250, 'ml'], t: [], img: 'cappuccino',
    n: ['Капучино', 'Cappuccino'],
    d: ['На альтернативном молоке +300 ₸', 'Plant milk available, +300 ₸'] },
  { id: 'cocoa', c: 'drinks', p: 1100, w: [250, 'ml'], t: ['kids'], img: 'cocoa',
    n: ['Горячий шоколад', 'Hot chocolate'],
    d: ['Густой, на молоке. Маршмеллоу по желанию', 'Thick and milky. Marshmallows on request'] },
  { id: 'lemonade', c: 'drinks', p: 900, w: null, t: ['new'], img: 'lemonade',
    n: ['Лимонад с мятой', 'Mint lemonade'],
    v: [{ l: ['Стакан 0,4 л', 'Glass, 0.4 l'], p: 900 }, { l: ['Кувшин 1 л', 'Jug, 1 l'], p: 1800 }],
    d: ['Лимон, лайм, свежая мята', 'Lemon, lime, fresh mint'] },
  { id: 'citrus', c: 'drinks', p: 1200, w: [400, 'ml'], t: [], img: 'citrus',
    n: ['Цитрусовый лимонад', 'Citrus lemonade'],
    d: ['Апельсин, грейпфрут, розмарин', 'Orange, grapefruit, rosemary'] },
  { id: 'mojito', c: 'drinks', p: 1300, w: [400, 'ml'], t: [], img: 'mojito',
    n: ['Мохито безалкогольный', 'Virgin mojito'],
    d: ['Лайм, мята, содовая', 'Lime, mint, soda'] },
  { id: 'iced-tea', c: 'drinks', p: 1100, w: [400, 'ml'], t: [], img: 'iced-tea',
    n: ['Холодный чай', 'Iced tea'],
    d: ['Чёрный чай, лимон, лайм', 'Black tea, lemon, lime'] },
  { id: 'juice', c: 'drinks', p: 1400, w: [300, 'ml'], t: ['kids'], img: 'juice',
    n: ['Свежевыжатый сок', 'Fresh juice'],
    d: ['Апельсин, яблоко или морковь', 'Orange, apple or carrot'] },
];

// «Любимое гостями» на главном экране
window.FEATURED = ['beshbarmak', 'pancakes', 'plov', 'lamb-skewer', 'medovik', 'milk-tea', 'manty'];

// Авторы фото с лицензиями CC (Unsplash не требует подписи)
window.PHOTO_CREDITS = [
  { img: 'beshbarmak', by: 'peretzp', lic: 'CC BY-SA 2.0', url: 'https://www.flickr.com/photos/68877611@N00/3991850909' },
  { img: 'borscht', by: 'avlxyz', lic: 'CC BY-SA 2.0', url: 'https://www.flickr.com/photos/10559879@N00/4643511529' },
  { img: 'plov', by: 'Boonlong1', lic: 'CC BY-ND 2.0', url: 'https://www.flickr.com/photos/10186213@N07/17181053501' },
];
